### PR TITLE
Setup husky and lint-staged

### LINKED ISSUE #66: [20/10/2022]: Set up Husky and Lint-staged
#### Description

- *Automate linting and formatting using husky and lint-staged packages*
- *This will ensure that a strict code style is enforced and reduce the bugs or coding errors that may arise as a result of several contributors working on the same codebase*
- *The parent issue is #10*

#### Which task are you working on?

- *Automating linting and code formatting using husky and lint staged*

### What needs to be done?

- [x] *Install `husky` and `lint-staged`*
- [x] *Set up pre-commit and pre-push hooks.*
- [x] *Configure `lint-staged` to work with `husky` in a `lint-staged.config.js` file*

### Who want to work on this issue?

*I would like to work and be assigned to this issue*

### PR DESCRIPTION
**Pull request by JulianaSau**
### Summary

Fixes #66 
Addresses #10 

*Automation of linting and code formatting to enforce a uniform code style for contributors on the repo*

### List of changes proposed in this PR (pull-request)

* *Install `husky`, `lint-staged`, `prettier`, `eslint` and their peer dependencies*
* *Set up `eslint` and `prettier` rules*
* *Configure `husky` and `lint-staged` to automate linting and formatting*
* *Ran `prettier --write` to fix the existing code formatting errors*
* *Ran `eslint --fix` to rectify the linting errors existing in the codebase*

### What should a reviewer concentrate their feedback on?

- [x] *The prettier formatting rules*
- [x] *The eslint configurations*
- [x] Everything looks ok?
- [x] Let me know if there's any change that i can remove or add to make this functionality work optimally

### CODE REVIEW

**Comment by sandygudie** [comment]
@JulianaSau  well done  on this 👏, it's great
 Please can you configure the pre-commit to fix Eslint and Prettier?
please let me know if you need clarity on this 
thanks

**Comment by JulianaSau** [comment]
> @JulianaSau well done on this 👏, it's great Please can you configure the pre-commit to run Eslint and Prettier fix? please let me know if you need clarity on this thanks

Hi. Thank you for reviewing my pr
I included this bit of code in the `lint-staged.config.js` to automatically fix up the auto-fixable errors
    ```bash
        module.exports = {
            '*.{js,jsx}': ['yarn lint'],
            '*.{js,json,css,jsx}': ['yarn format'],
          }
    ```

So the `pre-commit` hook runs the `lint-staged` scripts above included in the `package.json` file

**Review by sandygudie — APPROVED** [review]

**Comment by BatoolMM** [comment]
@all-contributors add @JulianaSau for infra

**Comment by BatoolMM** [comment]
@all-contributors add @JulianaSau for infra

**Comment by okerekechinweotito** [comment]
@JulianaSau  Good Job

**Pull request merged**
