### PR TITLE
Added frontend_project structure

### PR DESCRIPTION
**Pull request by sandygudie**
### Summary
Issue: [20](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/20)
PR : Added a  Frontend project structure for `dev_team2 `branch.

#### Activities
- Created a Frontend Folder in the root folder.
- Added Vitejs React project to the Frontend Folder
- Added a sample page to the folder

#### Project Structure
```
.....
Frontend/
  node_modules/
   public/
   src/
       -- components/
       --landing-page/
           -- index.jsx
           -- style.css
       --App.css   
       -- App.jsx 
       -- index.css
       -- main.jsx
index.html
vite.config.js
package.json
yarn.lock
...
```
To Run Project
- Navigate to the frontend folder from the root folder
- Run` yarn install` to install node_modules
- Run` npm run dev `to view project on localHost

### CODE REVIEW

**Comment by sandygudie** [comment]
@BatoolMM Please ready to merge to `dev_team2` branch

**Comment by BatoolMM** [comment]
Thank you @sandygudie, it's merged now!

**Comment by okerekechinweotito** [comment]
@sandygudie 
was this PR reviewed by anyone

**Comment by BatoolMM** [comment]
@all-contributors please add @sandygudie for infra

**Pull request merged**
