### PR TITLE
added authentication for sign-up page

### PR DESCRIPTION
**Pull request by sandygudie**
Fixes : https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/120

Fixes
Add Authentication and validation for Sign up page
Handle Errors and Responses to ensure user interactivity

### CODE REVIEW

**Comment by sandygudie** [comment]
@RealRichi3 
Please make this correction
image
just "Email already exists !" is okay

**Comment by RealRichi3** [comment]
Ohh, i'll change the response message then

**Comment by RealRichi3** [comment]
@sandygudie, i just checked the Front end, really good job, looks great

**Comment by RealRichi3** [comment]
I'm still testing the auth functionality tho, i'll give you feedback once i'm done

**Review by RealRichi3 — COMMENTED** [review]
The signup and email verification, works well, UI looks really good but, 
1. I think the delay timer for successful signup is a bit long.
2. I tried login, i didn't get any response

**Comment by sandygudie** [comment]
> The signup and email verification, works well, UI looks really good but,
> 
> 1. I think the delay timer for successful signup is a bit long.
> 2. I tried login, i didn't get any response

Thanks, 
Alright, I will reduce timer
I will work on the login after this

**Comment by RealRichi3** [comment]
> > The signup and email verification, works well, UI looks really good but,
> > 
> > 1. I think the delay timer for successful signup is a bit long.
> > 2. I tried login, i didn't get any response
> 
> Thanks, Alright, I will reduce the pop up display message, but if you are referring to the loading time before the pop up, that is sever related. I am work on the login after this

No i meant, when the success message pops up, it takes too long to leave the screen

**Pull request merged**
