### PR TITLE
admin can delete a course and user can get all courses

### PR DESCRIPTION
**Pull request by ORIYOMI289**
### Summary

*delete course API and get courses API*

### List of changes proposed in this PR (pull-request)

@BatoolMM @alswajiab 
* *authourize admin to delete course.*
* *registered users can see all courses*
* *add routes for CRUD operations for courses*
* *add delete and get course feature*
* *add restrictions for get courses route*

### What should a reviewer concentrate their feedback on?

- [x] *users can get courses*
- [x] *admin can delete a course*

### CODE REVIEW

**Review by RealRichi3 — COMMENTED** [review]
Thanks for the contribution @ORIYOMI289 , 
But for the `getCourses` function, i don't think you are returning a valid API response, plus you should also add the status code for the response

It should be more like

```
const courses = await Video.find().sort({_id: -1})

return res.status(200).send({ courses: courses})
```

Same thing for the delete course function, you can use
```
return res.status(200).send({message: "Successufully deleted course"})
```

**Comment by ORIYOMI289** [comment]
@RealRichi3 fixed now

**Comment by ORIYOMI289** [comment]
@RealRichi3 pls check now, I have fixed the branch now

**Comment by RealRichi3** [comment]
@ORIYOMI289 i added info to the PR description. Please when making changes to multiple files ensure you add an elaborate description.
Good one tho

**Comment by RealRichi3** [comment]
@ORIYOMI289 please add a reference to the sub issue you created for this PR

**Comment by ORIYOMI289** [comment]
@RealRichi3 the sub issue is here #51

**Comment by RealRichi3** [comment]
@ORIYOMI289 add it to the PR description

**Comment by BatoolMM** [comment]
@all-contributors add @ORIYOMI289 for infra

**Pull request merged**
