### PR TITLE
28/11/2022: Added Reset password feature

### PR DESCRIPTION
**Pull request by sandygudie**
fixes issue: https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/128

Description:
This PR includes
- Route set up and API for reset password
- Reset password UI page with authentication and validation
- Response and Error handling included

### CODE REVIEW

**Comment by sandygudie** [comment]
@RealRichi3  test here https://deploy-preview-129--oscsa-moocs.netlify.app/
I can't login with the new password

**Comment by RealRichi3** [comment]
@sandygudie alright, I'll check it out

**Comment by RealRichi3** [comment]
You're right, I think there's a bug somewhere, I'll fix it asap

**Comment by RealRichi3** [comment]
I'll raise an issue for it, and push a PR

**Comment by RealRichi3** [comment]
@sandygudie it's working now, ready to merge

**Review by RealRichi3 — APPROVED** [review]
Looking good, ready to merge

**Comment by sandygudie** [comment]
welldone @RealRichi3

**Comment by RealRichi3** [comment]
> welldone @RealRichi3 

You're welcome

**Pull request merged**
