### PR TITLE
[05/01/2023] [WIP] feat - Signin with google and github

### LINKED ISSUE #152: [05/01/2023] feat - Implement Signin with Google and Github
#### Description

For the backend API, implement social Sign in with google and github using passportjs

### What needs to be done?
- [x] *Add passport js*
- [x] *Add google Sign in*
- [x] *Add github Sign in*

### Who want to work on this issue?
I'll work on this issue

### PR DESCRIPTION
**Pull request by RealRichi3**
### Summary

Add Signin with google and github

Fixes #152

### List of changes proposed in this PR (pull-request)

* *Add passport js.*
* *Add google signin*
* *Add auth strategy for github*

### CODE REVIEW

**Comment by RealRichi3** [comment]
The backend api has been deployed, but i have merged this feature

**Comment by sandygudie** [comment]
Is it possible to test before merge?

**Comment by RealRichi3** [comment]
@sandygudie not sure if it's possible, don't worry I'll try to complete the feature today

**Comment by RealRichi3** [comment]
@sandygudie i've completed the google signin with passport.js, please review, I'll update the API doc

**Comment by RealRichi3** [comment]
@BatoolMM i've completed the features, please review

**Comment by RealRichi3** [comment]
There's one issue tho, i created an HTML file to act as the front end 
```html

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <button class="google"> Google signin </button>
    <script scr="https://www.gstatic.com/firebasejs/8.6.8/firebase-app.js"></script>
    <!-- axios -->
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <a href="http://localhost:5000/api/v1/auth/google">Google</a>

    <script>
        const googleButton = document.querySelector('.google');
        googleButton.addEventListener('click', () => {
            axios.get('http://localhost:5000/api/v1/auth/google')
                .then((res) => {
                    console.log(res);
                })
                .catch((err) => {
                    console.log(err);
                })
            })
    </script>
</body>

</html>
```

The HTML doc is hosted at `http://127.0.0.1:5501`

So there are two ways you can start the google signing, you can click the button or the anchor link.
Using the anchor link works fine, but when i try to use the button, i get this error
```bash
Access to XMLHttpRequest at 'https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=17364075701-av47bq1jg9qonicc9srmc59gddnk81vn.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A5000%2Fapi%2Fv1%2Fauth%2Fgoogle%2Fcallback&scope=openid%20profile%20email&state=KxnKuWZFBwxHXSRAUFyZOxMx' (redirected from 'http://localhost:5000/api/v1/auth/google') from origin 'http://127.0.0.1:5501' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

I could've gone with the anchor link method, but i after the auth process the backend API sends an accessToken, and i don't know if @sandygudie would be able to get the response

I tried adding the path `http://127.0.0.1:5501` to the Authorized Javascript origins for the google Oauth API credentials 
image

But it still doesn't work

**Comment by RealRichi3** [comment]
I even tried to use a proxy middleware for the router, but it still didn't work. I'll just switch to the normal implementation in the google Documentation

**Comment by BatoolMM** [comment]
@RealRichi3 When you implemented `passport` for Google Sign in, did you also use `express-session`, `passport-local`, `passport-local-mongoose`?

Just to double-check because when I reviewed the code I couldn't locate them imported to you script?

**Comment by RealRichi3** [comment]
I used `express-session` is was used in the `/backend_API/src/app.js` file, i didn't use `passport-local` and `passport-local-mongoose`, i used the

**Comment by RealRichi3** [comment]
@BatoolMM, i think it's good to go now, the google and github signin features are working fine

**Comment by sandygudie** [comment]
@RealRichi3, i will like to join in testing the backend Api,
Can you share your environment variables, I will test locally

**Comment by RealRichi3** [comment]
Alright I'll share them with you

**Comment by BatoolMM** [comment]
@RealRichi3 can you also share them with me, so I can add them to the repo sittings?

**Comment by RealRichi3** [comment]
@BatoolMM i sent it on keybase

**Comment by BatoolMM** [comment]
Feel free to merge when ready!

**Pull request merged**
