### PR TITLE
[29/01/2023] feat: combine documentation for CLIENT and API

### PR DESCRIPTION
**Pull request by RealRichi3**
### Summary

Combine the documentation for both the `CLIENT` and `API`

### List of changes proposed in this PR (pull-request)
* *Setup JSDOC*
* *Setup templates*
* *Combine documentation for both frontend and backend*

### CODE REVIEW

**Comment by RealRichi3** [comment]
Pardon the many changes, i merged the recent updates from the `frontend_dev` and `backend_dev`

**Comment by sandygudie** [comment]
> Pardon the many changes, i merged the recent updates from the `frontend_dev` and `backend_dev`

Welldone @RealRichi3 can you deploy the doc, let’s see what it looks like?

**Comment by RealRichi3** [comment]
Alright @sandygudie, the doc isn't clean yet, i just laid down the structure and the themes, I'll merge this and raise a new PR to add the contents to the doc

**Comment by RealRichi3** [comment]
@sandygudie, please raise a PR from the `frontend_dev` to `dev`, i'll need the updated data to work on the doc

**Pull request merged**
