### PR TITLE
[29/11/2022] Change password reset authentication flow

### LINKED ISSUE #133: [29/11/2022] - Change Password reset authentication flow
#### Description

- Change the authentication flow for forgotpassword and passwordreset flow.
- Instead of sending URL link with embedded token, send a short term access token to the front end.
- The email sent to the user should only contain a 6 digit code..

/forgotpassword request should be called before the /passwordreset route.
### /forgotpassword
- Generate 6 digit password reset code, send code to users email.
- Send JWT access token to the front end, it should only last for a short time.

### /passwordreset
- Request body should include 6 digit reset code and new password 
- Authentication header should have access token as bearer token
- Update users new password

### What needs to be done?
- [x] *Add Database model to store authentication codes (password_reset code)*
- [x] *Send random password reset code to users email*
- [x] *Send JWT token to front end, should have short expiry*

### PR DESCRIPTION
**Pull request by RealRichi3**
### Summary
Change /forgotpassword and /resetpassword flow to implement password reset code and JWT access token 

Fixes #133, Supports #127

### List of changes proposed in this PR (pull-request)
- [x] *Add Database model to store authentication codes (password_reset code)*
- [x] *Send random password reset code to users email*
- [x] *Send JWT token to front end, should have short expiry*
- [x] *Test new auth flow*
- [x] *Add get logged in user feature*

### CODE REVIEW

**Comment by sandygudie** [comment]
Hi @RealRichi3  i tested the endpoints with postman , I did not get the intended response

**Comment by RealRichi3** [comment]
What response were you getting?

**Comment by RealRichi3** [comment]
Sorry, i just checked Render and deployed the most recent update

**Comment by sandygudie** [comment]
@RealRichi3 reset link is showing undefined
image

**Comment by RealRichi3** [comment]
@sandygudie alright, i'll check it out

**Comment by RealRichi3** [comment]
@sandygudie, i just fixed it now, will deploy the new changes

**Comment by RealRichi3** [comment]
Done

**Pull request merged**
