### PR TITLE
FrontEnd project structure and route

### PR DESCRIPTION
**Pull request by mufidat3250**
### Summary
Setup the Frontend folder structure  and the route from  issue https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/10

.....
- frontend /
   - node_modules/
   - public/
     - vectors/
     - images/
   - src/
       - components/
         - atom/
           - Button/
             - Button.jsx
             - Button.css
            - Input
              - Input.jsx
              - input.css   
         - molecule/
            - Header/
               - Header.jsx
               - Header.css 
            - Footer/
              - Footer.jsx
              - Footer.css   
         - organisms/
       - pages/
         - Amin/
            - Admin.jsx
            - Admin.css
         - CourseDetails/
            - Courses.jsx
            - courses.css
         - History/
            - History.jsx
            - History.css
         - Home/
            - Home.jsx
            - Home.css         - 
         - Login/
            - Login.jsx
            - Login.css
         - Signup/
            - Signup.jsx
            - SignUp.css
         - Profile/
            - Profile.jsx
            - Profile.css
         - Settings/
            - Setting.jsx
            - Settings.css
       - template/
         - DashboardLayout/
            - DashboardLayout.jsx
            - DashboardLayout.css
         - PageLayout/
            - PageLayout.jsx
            - PageLayout.css
       - .env
       - App.js
    - package-lock.json
    - package.json

Fixes issues  https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/16

### List of changes proposed in this PR (pull-request)

* * Project Created Project Structure for front end*
* *Routed All the available pages with react-router dom v6*

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### CODE REVIEW

**Comment by BatoolMM** [comment]
@mufidat3250 Thank you for your work, can you please make sure the title is describing what this PR is about?

**Comment by mufidat3250** [comment]
Alright done @BatoolMM

**Comment by mufidat3250** [comment]
@BatoolMM  pls i want to ask  why do we have two branch for the frontend  the dev and dev_team2  what is the difference?

**Comment by Dhei-vid** [comment]
> @BatoolMM pls i want to ask why do we have two branch for the frontend the dev and dev_team2 what is the difference?

dev is the main branch where other teams can fork to create their own project. dev_team2 is specific to us.

**Comment by BatoolMM** [comment]
Hi @Dhei-vid, what is the condition of this branch?
tagging @RealRichi3 and sandygudie!

**Comment by Dhei-vid** [comment]
@BatoolMM I think @mufidat3250 would have more information on that.

**Comment by BatoolMM** [comment]
Thank you @Dhei-vid!

**Comment by mufidat3250** [comment]
@BatoolMM I was not aware that the dev_team2  is the branch we are to be making pull request to not until @Dhei-vid made some clarifications.

**Comment by sandygudie** [comment]
@mufidat3250  i would close this pull request since you won't be using it anymore

**Pull request closed without merging**
