### PR TITLE
[17/10/2022] : removed packages not needed

### PR DESCRIPTION
**Pull request by sandygudie**
### Summary Issue:[ 40](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/40)
FRONTEND DEVELOPMENT FOR THE MOOCS PLATFORM: dev_team2 branch
The last PR merged was not reviewed, some packages not needed were installed. This PR is a work around in ensuring the project is in order as planned.

Fixes #<NUM>
* Remove material UI styling library and it's component files
* Remove `package.json.lock` , we using `Yarn ` for Package Manager

### What should a reviewer concentrate their feedback on?
- The project is working fine

### CODE REVIEW

**Comment by sandygudie** [comment]
@BatoolMM, Please this is ready for merge

**Review by Meekunn — APPROVED** [review]
This looks good. 👍 @sandygudie

**Comment by BatoolMM** [comment]
What is the last PR that has some packages which are not needed were installed? Can you reference its number within the description of the PR.

**Comment by sandygudie** [comment]
@BatoolMM it's PR https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/31

**Comment by BatoolMM** [comment]
Thank you @sandygudie!

**Pull request merged**
