### PR TITLE
[17/10/2022]Develop Header and Footer Section

### LINKED ISSUE #19: [14-10-2022]: Develop Header and Footer for MOOC App
#### Description
Develop the Header and Footer section of the MOOC App referencing the Design template from issue #11. 

#### Which task are you working on?

- [ ] *Develop Header.*
- [ ] *Develop Footer.*

### What needs to be done?

- [ ] *Develop Header and Footer Section*

### Who want to work on this issue?

Kindly assign to me, @BatoolMM. I want to work on this issue and follow up on updates from Parent issue #10.

### PR DESCRIPTION
**Pull request by Meekunn**
### Summary

*Develop Header Section.*
*Develop Footer Section.*
Fixes #19  

### List of changes proposed in this PR (pull request)

* *Install new dependency: react-icons*
* *Create a new folder, Navbar, in `Frontend/components`*
* *Create `Navbar.jsx` and `navbar.css` in `Frontend/components/Navbar`*
* * *Create a new folder, Footer, in `Frontend/components`*
* *Create `Footer.jsx` and `footer.css` in `Frontend/components/Footer`*

### What should a reviewer concentrate their feedback on?

- [x] *Header Section*
- [x] *Footer Section*
Everything looks ok?

Screenshot from 2022-10-15 23-55-02
Screenshot from 2022-10-17 12-18-24

### CODE REVIEW

**Comment by sandygudie** [comment]
Welldone @Meekunn the login and signup page is great. The changes needed:
-Responsiveness: the header is not responsive, I am seeing the mobile view on my desktop, please look into your media query screen width.
- I noticed you installed material UI Library, I am not sure we will be using it and we have to avoid loading libraries into the project for performance's sake.
- Please install node modules using `yarn install` to ensure package consistency.

Please feel free to reach out if you need further clarity

**Comment by Meekunn** [comment]
@sandygudie Thanks, I'll fix the media queries. As for the package installation, that wasn't me. I only installed react-icons as stated in the PR. Material-UI was installed when I pulled the changes for dev_team2 branch so I decided to use some components from the library. Also, the changes in the dev_team2 branch had both yarn.lock and package-lock.json, so I decided to use `npm install` to ensure package consistency. If there won't be a use for `npm install`, I suggest you delete the package-lock.json.  Thank you.

**Comment by sandygudie** [comment]
@Meekunn 
Yeah, I just noticed that a PR was merged without review, I will work on that just go ahead and work on your part. Thank you

**Comment by Meekunn** [comment]
I just noticed. I wasn't the one who developed the Login and SIgnUp page. Also, the pages developed doesn't follow the design in the figma file. Are we allowed to apply our designs? @sandygudie

**Comment by sandygudie** [comment]
I just noticed it too, it was merged without reviewed. Since it looks great we can keep for now.

**Comment by mufidat3250** [comment]
@sandygudie i created an issue to implement the landing page but it has not yet being assigned to me but i have stared working on it hope there is no issue with that and hope there is no problem with modifying the design as i noticed that some of the colors and font needs modification for good user experience. or i should just go with what is in the design

**Comment by sandygudie** [comment]
Go ahead with what you have you, it would be decided when it’s reviewed

**Comment by mufidat3250** [comment]
@sandygudie alright

**Comment by Meekunn** [comment]
@sandygudie I made corrections, kindly review. Thanks.

**Comment by sandygudie** [comment]
Alright @Meekunn

**Comment by Meekunn** [comment]
@sandygudie Developed the Footer Section and updated the comment on this PR, kindly review. 

Thanks. 😊

**Comment by sandygudie** [comment]
Welldone, @Meekunn  i am waiting for @BatoolMM  to merge this [PR ](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/39) so that you can pull updated files.
I will review your PR while waiting on that

**Comment by BatoolMM** [comment]
Can you resolve the conflict in this PR, please?

**Comment by sandygudie** [comment]
Hi @Meekunn Welldone for the header and footer, the navbar works well now, suggested changes:
- Footer- the footer font size is a bit large, let's use `font-size: 1rem` for the normal text and `font-size:1.5rem` for the h2 tags(contact, etc). The result is this
image

Responsiveness- Footer
- remove the `width:70%` or make `width:100%` on the `footer wrapper` for the mobile view to prevent the text from breaking
image

- Pull updates and fix conflict

**Comment by sandygudie** [comment]
@mufidat3250 Please also review this PR and drop your thoughts thanks

**Comment by Meekunn** [comment]
@mufidat3250, thanks for your review, I have made adjustments. @BatoolMM Conflict has been resolved, kindly merge. Thanks 😊

**Comment by BatoolMM** [comment]
@all-contributors please add @Meekunn for design

**Comment by BatoolMM** [comment]
@sandygudie can you review this PR, please?

**Comment by sandygudie** [comment]
> @sandygudie can you review this PR, please?

Alright @BatoolMM

**Comment by sandygudie** [comment]
The Hamburger Menu; Sidebar
- The signup button is cut off
- The main body is scrolling instead of the sidebar, I will suggest you add it to the items up there,
- Reduce the close icon size abit
image
https://loom.com/share/0d4401b428e148cc8fa74cb818041170

**Comment by Meekunn** [comment]
@sandygudie, I fixed the auth buttons' position and icon size. As for the Sidebar scrolling. I don't think the sidebar is meant to scroll because it doesn't have any overflowing contents. Kindly review and tag @BatoolMM to merge this PR so I can move on to another task. Thanks. 😊

**Comment by okerekechinweotito** [comment]
@Meekunn good job 👍

**Comment by sandygudie** [comment]
> @Meekunn Please a couple of suggested changes,
> 
> * a) reduce the size of the logo on the desktop and mobile view ( use header size)
> * b) reduce the "lorum" text font-size `font-size:1rem`
>   image

Welldone @Meekunn you did not add the suggested changes to the footer.

**Comment by Meekunn** [comment]
@sandygudie, Done. Kindly review and tag @BatoolMM to merge. Thanks

**Review by sandygudie — APPROVED** [review]

**Comment by sandygudie** [comment]
@Meekunn please fix conflict
Thanks

**Comment by Meekunn** [comment]
@sandygudie, Conflicts are fixed and PR is ready to be merged.

**Comment by okerekechinweotito** [comment]
@BatoolMM Please Merge

**Pull request merged**
