### PR TITLE
Deploy the new translation for the front-end

### PR DESCRIPTION
**Pull request by BatoolMM**
### Summary

this is to merge translations.

Fixes #<NUM>

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

### List of changes proposed in this PR (pull-request)

* *Lorem ipsum dolor sit amet, consectetur adipiscing.*
* *Lorem ipsum dolor sit amet, consectetur adipiscing.*

### What should a reviewer concentrate their feedback on?

- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
- [ ] Everything looks ok?

### CODE REVIEW

**Comment by BatoolMM** [comment]
@sandygudie the new translation is not reflected on the deployment - not sure why?

**Comment by sandygudie** [comment]
> @sandygudie the new translation is not reflected on the deployment - not sure why?

Noted, I will look into it

**Review by sandygudie — COMMENTED** [review]
Hi @BatoolMM  i have extracted and compile the frontend-ui branch.
Please review the translation update.

**Comment by BatoolMM** [comment]
Hi @sandygudie - thank you so much - there is no deployment to preview?

**Comment by sandygudie** [comment]
Yes i saw that too, i will trigger a deploy.

**Comment by sandygudie** [comment]
@BatoolMM it's the preview link is ready

> ### ✅ Deploy Preview for _moocs-client-sub_ ready!
> Name	Link
> 🔨 Latest commit	
> 🔍 Latest deploy log	https://app.netlify.com/sites/moocs-client-sub/deploys/65b16222a64cb646956e2790
> 😎 Deploy Preview	https://deploy-preview-311--moocs-client-sub.netlify.app
> 📱 Preview on mobile	
> Toggle QR Code...
> _To edit notification comments on pull requests, go to your [Netlify site configuration](https://app.netlify.com/sites/moocs-client-sub/configuration/deploys#deploy-notifications)._

**Comment by BatoolMM** [comment]
This is amazing, thank you @sandygudie - I will merge it. Once it is merged, would you mind to take a screenshot from your machine because the font look prettier in your machine.

**Comment by sandygudie** [comment]
The translation on the site is repeated 
https://deploy-preview-311--moocs-client-sub.netlify.app/

**Comment by BatoolMM** [comment]
I can't approve or merge because I was the one who opened the PR - can you merge it, pls?

**Comment by sandygudie** [comment]
Alright, the deployment, is it ohkay

Screenshot 2024-01-24 at 20 30 49

**Comment by BatoolMM** [comment]
Thank you @sandygudie - amazing 🤩

**Pull request merged**
