### PR TITLE
[10/1/2023]: Jsdocs pages

### PR DESCRIPTION
**Pull request by sandygudie**
Description
fixes issue: https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/154

This PR is a continuation of [PR](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/155). 
The PR includes the generated JSdocs pages. The pages will be deployed Netlify.

Documentation Link: https://moocs-jsdocs.netlify.app/

### CODE REVIEW

**Comment by BatoolMM** [comment]
Thank you @sandygudie 🌷 
Can you deploy it on GitHub pages and add the link to the description?

**Comment by BatoolMM** [comment]
Can you also add the changes to the `CHANGELOG.md` file, please

**Comment by sandygudie** [comment]
> Thank you @sandygudie 🌷 Can you deploy it on GitHub pages and add the link to the description?

Hi @BatoolMM , I have a bit of challenge deploying the jsdocs folder to github pages. The jsdocs  folder is in the frontend folder which is not recognize on github pages selection 
image
I am hoping I could find a workaround on how to deploy subfolder to github pages. if it's not possible, I will try deploying on with netlify

**Comment by BatoolMM** [comment]
@sandygudie No worries, try Netlify!

**Comment by BatoolMM** [comment]
Feel free to merge when ready!

**Comment by sandygudie** [comment]
> @sandygudie No worries, try Netlify!

Documentation Link: https://moocs-jsdocs.netlify.app/

**Comment by BatoolMM** [comment]
Amazing, thank you @sandygudie. Can you add the link to the README, please?

**Review by BatoolMM — APPROVED** [review]

**Comment by sandygudie** [comment]
@BatoolMM I will like to request access to deploy directly from the organization, I am getting this message on netlify. The deployment above is from my forked repository and if changes are made to the origin branch, the jsdocs page will not auto-deploy because it's from my forked repo.
Screenshot (60)

Also, I will merge this branch to the frontend_dev branch hence I will have to do another deployment for the JSDoc from the frontend_dev.
What would you recommend?

**Comment by sandygudie** [comment]
> Amazing, thank you @sandygudie. Can you add the link to the README, please?

The home page is the link to the readme file, I will also include a Link on the side bar too

**Pull request merged**
