### PR TITLE
Frontend Project Setup

### LINKED ISSUE #12: [13/10/2022]: Setup Frontend for MOOC Platform
#### Description
I would like to set up the Frontend for the OSCSA MOOC PLATFORM.
The parent Issue is #10 

#### Which task are you working on?

- [ ] *Create React App in `dev` branch*
- [ ] *Task 1- Set Up Prettier/Eslint*

#### Who wants to work on this issue?
I would like to work on this issue @BatoolMM and follow updates on the parent issue

### PR DESCRIPTION
**Pull request by Meekunn**
### Summary

*Create React-App and Setup Eslint and Prettier.*

```
.....
frontend/
  -- .vscode/
    -- settings.json
  -- node_modules/
  -- public/
    -- index.html
  -- src/
       -- App.css
       -- App.js
       -- index.css
       -- index.css
  -- .eslintrc.json
  -- .eslintignore
  -- .prettierrc.json
  -- .prettierignore
  -- .gitignore
  -- package.json
  -- package-lock.json
  --README.md
```
Fixes #12 

### List of changes proposed in this PR (pull request)

- [x] *Create React App*
- [x] *Setup Eslint and Prettier* 

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### CODE REVIEW

**Comment by Meekunn** [comment]
@BatoolMM 
This PR sets up the Frontend Project Structure as explained in issue #10, kindly review and merge so others can start tasks and contribute. Thank you.

**Comment by BatoolMM** [comment]
Thank you for your amazing work, all!

**Comment by BatoolMM** [comment]
@all-contributors add @Meekunn for infrastructure

**Comment by BatoolMM** [comment]
https://github.com/all-contributors add @BatoolMM for review

**Comment by BatoolMM** [comment]
@all-contributors add @BatoolMM for mentoring, question, translation, review

**Pull request merged**
