### PR TITLE
[12/10/2022]: Backend API (feat) - Project structure

### PR DESCRIPTION
**Pull request by RealRichi3**
### Summary
Setup NodeJS MVC app structure for the BACKEND API for MOOCs platform issue #5 
```
.....
backend_API/
  -- node_modules/
  -- src/
       -- controllers/
       -- routes/
           -- routes_handler.js
       -- models/
       -- db/
       -- test/
       -- utils/
             -- async_wrapper.js
             -- config.js
       -- .env
       -- app.js
       -- server.js
package-lock.json
package.json
```

Fixes issue #13

### List of changes proposed in this PR (pull-request)
* Added project structure for backend API
* Added database connection 
* Setup MVC app structure

### What should a reviewer concentrate their feedback on?
- [x] Everything looks ok?

### CODE REVIEW

**Comment by RealRichi3** [comment]
@BatoolMM  this is  the pull request to add the Backend API project structure as explained in issue #5. 
Please review and merge to `dev` branch so others can pull and start working on the tasks

**Comment by BatoolMM** [comment]
Thank you @RealRichi3 for your hard work! 

Just to double-check, I just merged PR #14 for dev branch. Would you like to have your work at the same dev branch or I can create another one if you are working in different groups?

**Comment by RealRichi3** [comment]
Thanks @BatoolMM, i would be better to work on a different branch, but we were hoping to discuss more on that tomorrow

**Comment by BatoolMM** [comment]
I created a [new branch called `dev_team2`](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/tree/dev_team2) just in case you want to use it.

**Comment by RealRichi3** [comment]
Perfect, but will the zoom session for tomorrow still hold?

**Comment by BatoolMM** [comment]
Hi @RealRichi3, I am very sorry that this will be postponed till Tuesday at the same time. This was outside our control, but we are happy to support you and answer questions you have. I think the best way to resolve this PR is to create another one directed toward a [dev_team2](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/tree/dev_team2) branch. Let us know if you want to proceed using a different approach, @alswajiab and I will help you with it 🌻

**Comment by BatoolMM** [comment]
> Hi @RealRichi3, I am very sorry that this will be postponed till Tuesday at the same time. This was outside our control, but we are happy to support you and answer questions you have. I think the best way to resolve this PR is to create another one directed toward a [dev_team2](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/tree/dev_team2) branch. Let us know if you want to proceed using a different approach, @alswajiab and I will help you with it 🌻

**Comment by BatoolMM** [comment]
Apologies, it was closed by mistake, it is re-opened now!

**Comment by RealRichi3** [comment]
> Hi @RealRichi3, I am very sorry that this will be postponed till Tuesday at the same time. This was outside our control, but we are happy to support you and answer questions you have. I think the best way to resolve this PR is to create another one directed toward a [dev_team2](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/tree/dev_team2) branch. Let us know if you want to proceed using a different approach, @alswajiab and I will help you with it 🌻

Alright, i guess we'll go with it. The issue i had was that, since the project plan has been set in issue #5, every pull request to the branch has to be reviewed so it'll be inline with the project plan, i'd like to suggest that i should review all pull request made to `dev_team2`, if it's ready for merge then i can tag you saying 'reviewed and ready to merge'.

**Comment by RealRichi3** [comment]
Another idea.

Since the backend and frontend are part of the main plan in issue #2, we can just use one branch, then two separate folders in it, the front end work will be done in the `frontend` folder, then the code for backend will de done in `backend`. I think this will be good so we won't need to open so many branches. 
This way it'll be one branch per proposal

For this proposal @sandyguide can review all PR related to the frontend issue #10
And I can review all PR related to backend api issue #5

Once reviewed we can just comment `reviewed and ready to merge` then you can merge. This way it'll be inline with the main proposal in #2 and collaboration for #10 and #5 would be more effective

**Comment by BatoolMM** [comment]
I love the way you have been managing and organising the protject @RealRichi3. I created a new tag `ready to merge`. Feel free to use it and either me or @alswajiab will merge your PR. Let us know if you need any other thing!

**Comment by sandygudie** [comment]
> Another idea.
> 
> Since the backend and frontend are part of the main plan in issue #2, we can just use one branch, then two separate folders in it, the front end work will be done in the `frontend` folder, then the code for backend will de done in `backend`. I think this will be good so we won't need to open so many branches. This way it'll be one branch per proposal
> 
> For this proposal @sandyguide can review all PR related to the frontend issue #10 And I can review all PR related to backend api issue #5
> 
> Once reviewed we can just comment `reviewed and ready to merge` then you can merge. This way it'll be inline with the main proposal in #2 and collaboration for #10 and #5 would be more effective

I agree with this, @BatoolMM, please merge the backend project set up [PR](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/14) to the [dev ](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/tree/dev) branch , so we commenced from there.

**Comment by sandygudie** [comment]
@RealRichi3 just to be sure, are we using the` dev` branch or` dev_team` branch

**Comment by RealRichi3** [comment]
@sandygudie let's go for the `dev_team`

**Comment by RealRichi3** [comment]
> I love the way you have been managing and organising the protject @RealRichi3. I created a new tag `ready to merge`. Feel free to use it and either me or @alswajiab will merge your PR. Let us know if you need any other thing!

Thanks @BatoolMM, i Will make the PR to `dev_team` so we can start contributing

**Comment by sandygudie** [comment]
Also then, i will set up a frontend structure  for` dev_team` branch

**Comment by RealRichi3** [comment]
Sorry it's `dev_team2`

**Comment by RealRichi3** [comment]
@sandygudie it's `dev_team2` not `dev_team`

**Comment by RealRichi3** [comment]
@BatoolMM it's ready to merge now

**Comment by RealRichi3** [comment]
> I love the way you have been managing and organising the protject @RealRichi3. I created a new tag `ready to merge`. Feel free to use it and either me or @alswajiab will merge your PR. Let us know if you need any other thing!

@BatoolMM  how do we add the `ready to merge` tag?

**Comment by BatoolMM** [comment]
Brilliant, it's merged now!

**Comment by BatoolMM** [comment]
@RealRichi3 , let me know if you still can't access `ready to merge` tag!

**Pull request merged**
