### PR TITLE
[18-10-2022] Password Reset Feature

### LINKED ISSUE #42: [17-10-2022]: Authentication Feature: Password Reset
#### Description

- [x] *Password Reset.*
- [ ] *Email Verification to complete signup.*

#### Which task are you working on?

- [x] *Send reset token via email to user*
- [ ] *Reset Password*
- [x] *Save new password in database*

### Who want to work on this issue?

I would work on this issue
Parent Issue: #5

### PR DESCRIPTION
**Pull request by anslemkelechi**
### Summary

Fixes #42 

*Fixes the password reset functionality*

### List of changes proposed in this PR (pull-request)

* Added New Schema Methods To Handle The Generation Of Reset Tokens
* Created New Route For Forgot Password
* Send Reset Token To User Email (I Used Mailtrap.io for testing)
* Created New Route To Handle The Reset Of Password
* Handle and Make Patch Request To The API To Update The Password.

### What should a reviewer concentrate their feedback on?

Authentication Feature: Password Reset
Parent Issue : #5 
Sub Issue: #42

### CODE REVIEW

**Comment by RealRichi3** [comment]
@BatoolMM please merge

**Comment by anslemkelechi** [comment]
> @BatoolMM please merge

Thanks, @RealRichi3 
I was about to mention you.

**Comment by RealRichi3** [comment]
You're welcome

**Comment by BatoolMM** [comment]
Can you resolve conflicts, please?

**Comment by BatoolMM** [comment]
@all-contributors please add @anslemkelechi for infra

**Comment by BatoolMM** [comment]
https://github.com/all-contributors please add @RealRichi3 for review

**Comment by RealRichi3** [comment]
@anslemkelechi 
I'm trying to create the unit test for the password reset feature. I can only get the reset token from the message sent to my email. But i don't want to make calls to any gmail API to read the last email and get the reset token.
What i had in mind was to get the saved hash from the db and reverse the hash to get the reset token, then use it to run the test for the endpoint. But i don't know how to reverse the hash using the `crypto` module.

Is there a way to get the original resetToken by reversing the hash, if there is a way, how can i do it?

https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/blob/63b05b771baa60601650e74e9a8e91aa86bc34d0/backend_API/src/models/user.models.js#L90-L98

**Comment by anslemkelechi** [comment]
Hi @RealRichi3, sorry for the late response, you would not be able to reverse the hash, because it wasn't encrypted rather it was hashed, the only two solutions to this could be 

1. We can use encryption instead of hashing [you can use this link to see how it's done](https://www.section.io/engineering-education/data-encryption-and-decryption-in-node-js-using-crypto/)

2. We save the resettoken it self to the db.

**Comment by RealRichi3** [comment]
@anslemkelechi thanks

**Comment by RealRichi3** [comment]
I'm thinking of creating a separate collection to store the unhashed token, then use this collection strictly for tests

**Pull request merged**
