### PR TITLE
[15/10/2022] Backend API - Created Course/Video Database Models

### PR DESCRIPTION
**Pull request by oEbuka**
[15/10/2022] Backend API [feat] - Created Course/Video Database Models.

### Summary

Create the database models for Course/Video and also added a model for Categories which was not in the initial template.

### List of changes proposed in this PR (pull-request)

Models created using mongoose( MongoDB ).
Model created for Course/Video.
Category model also added and created.

### What should a reviewer concentrate their feedback on?
- [ ] Course Model Task for Backend. Parent issue:  https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/5#issue-1406773854

### CODE REVIEW

**Comment by RealRichi3** [comment]
@oEbuka thanks for the contribution, but the user and password models has already been created

**Comment by oEbuka** [comment]
> @oEbuka thanks for the contribution, but the user and password models has already been created

Yes I realized that's whi I deleted them.

**Comment by RealRichi3** [comment]
It has merge conflicts, you should pull the existing changes in the `dev_team2` branch before making more changes.
I think if this PR gets merged the empty files model files would override what's already saved

**Comment by RealRichi3** [comment]
Nice one, but @oEbuka You removed the code in password.models.js and user.models.js

**Comment by oEbuka** [comment]
> Nice one, but @oEbuka You removed the code in password.models.js and user.models.js

Apologies, added now.

**Comment by oEbuka** [comment]
@BatoolMM @alswajiab please review and merge

**Comment by RealRichi3** [comment]
@BatoolMM  please review and merge

**Comment by BatoolMM** [comment]
Can you resolve the conflicts, please?

**Comment by ORIYOMI289** [comment]
@oEbuka I can't find the video or course model you created, I am working on  the CRUD apis

**Comment by BatoolMM** [comment]
@all-contributors please add @oEbuka for Infrastructure

**Comment by BatoolMM** [comment]
@all-contributors please add @RealRichi3 for review

**Pull request merged**
