### PR TITLE
[17/10/2022] Develop the landing Page

### PR DESCRIPTION
**Pull request by mufidat3250**
### Summary

Developed the landing page

Fixes #<https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/36>

### List of changes proposed in this PR (pull-request)

*created component folder
* *created the  folder listed below  in the component folder
     -button 
     -Carousel 
     -Coursecard
     -learning widget 
     -records
      -testimonial
      -vectors*
* *Created landing-page Folder  in the pages folder*
* *Created an image folder in the public folder*
* Installed react-slick for the carousel 
* the vector folder created is to house all the icons i converted to component

### What should a reviewer concentrate their feedback on?

- [X] *Hero section*
- [X] *Course Carousel*
- [X] *Student testimonial section*
- [X] *Instructor section*
- [X] *Mobile responsive screen*
- [X] *Tab responsive screen*
- [x] *Desktop responsive screen*
- [X] Everything looks ok?

**Mobile**
mobile1

mobilecarouselcorect
mobile3

mobile4

mobile5

**Tablet**
ta1

tabcarouselcorect

tab3
tab4

tab5

**Desktop**
desktop1

desktopCarouselcorect
desktop3
desktop4

testimonialcorrection

@BatoolMM  kindly review

### CODE REVIEW

**Comment by mufidat3250** [comment]
@sandygudie  @BatoolMM  i made a pull request to the dev_team2 branch kindly review

**Comment by mufidat3250** [comment]
@sandygudie pls help check if there is anything i am doing wrong that need to be corrected

**Comment by sandygudie** [comment]
Alright @mufidat3250

**Comment by BatoolMM** [comment]
Can you resolve the conflict, please?

**Comment by sandygudie** [comment]
@Meekunn please join me to review this PR

**Comment by sandygudie** [comment]
Welldone @mufidat3250 for working on the landing page, a couple of changes are needed:
- Responsiveness- Please work on the responsiveness
- Increase the width `width :15rem`
image
- increase the width of the carousel images
image
- Typo Error
image
- Make this a clickable button ( add` cursor:pointer` and hover effect too)
image
- Remember to pull updates and fix conflicts
Thanks

**Comment by mufidat3250** [comment]
@sandygudie Alright

**Comment by BatoolMM** [comment]
@all-contributors please add @mufidat3250 for Design

**Comment by BatoolMM** [comment]
https://github.com/all-contributors please add @sandygudie for review

**Comment by BatoolMM** [comment]
Can you resolve conflict, please?

**Comment by sandygudie** [comment]
@Teslimsama i will suggest you get the color code from the figma design

**Comment by mufidat3250** [comment]
@sandygudie    I just pulled from dev_team2 and i noticed i have both yarnlock and package-lock.json  i want to ask if i should delete the package- lock.json
yarnLock issues

pls i have issues resolving this,  it all started when i pull from the dev_team2 branch and  there was  a pop up  under it stating that i should merge in editor on clicking it i got stuck on how to move forward.  I need to be unblock. will really appreciate your help

**Comment by sandygudie** [comment]
@mufidat3250  do this
Delete the yarn lock file
Delete the package.json lock file
delete your node modules
Go to the repo , Copy the updated files on the package.json(dev_team branch) and replace it with yours
Run a new yarn install

let me know how it goes

**Comment by okerekechinweotito** [comment]
@mufidat3250  This looks good !  Good Job

**Comment by mufidat3250** [comment]
> @mufidat3250 This looks good ! Good Job
@okerekechinweotito  Thanks alot

**Comment by mufidat3250** [comment]
> @mufidat3250 do this Delete the yarn lock file Delete the package.json lock file delete your node modules Go to the repo , Copy the updated files on the package.json(dev_team branch) and replace it with yours Run a new yarn install
> 
> let me know how it goes

I was able to resolve it with this thanks alot

**Comment by mufidat3250** [comment]
@sandygudie  kindly review the PR I have effected the changes and worked on the responsiveness.

**Comment by sandygudie** [comment]
Hi @mufidat3250 
I mentioned a couple of changes here
https://loom.com/share/38cefd1b17724d6bbe6b6d03144832fb
let me know if you have questions

**Comment by mufidat3250** [comment]
@sandygudie thanks for the observation,  what alternative can i use for view height.

**Comment by mufidat3250** [comment]
@sandygudie I am done with the corrections you can check it out.

**Comment by sandygudie** [comment]
Please fix the conflict @mufidat3250

**Comment by mufidat3250** [comment]
@sandygudie Done

**Comment by mufidat3250** [comment]
@sandygudie  have you checked it is there anything else i need to do?

**Comment by mufidat3250** [comment]
@sandygudie what else do i need to do for the code to be merged

**Comment by sandygudie** [comment]
@mufidat3250 
i will review

**Comment by mufidat3250** [comment]
@okerekechinweotito @sandygudie  kindly check my PR as i am still awaiting the update from the review.

**Comment by sandygudie** [comment]
Hi @mufidat3250 
A couple of changes for the page

- The red background is not needed
image

- The button does not have a smooth hover, it's shaking
image

- Responsiveness issues: Remove all  **height : vh** in media queries at width: 768px
image

**Comment by sandygudie** [comment]
@RealRichi3, Please review this page thanks, what do you think?

**Comment by RealRichi3** [comment]
@sandyguide please where's the deployed link

**Comment by sandygudie** [comment]
We use the Netflix deployed Preview 

> ### ✅ Deploy Preview for _oscsa-moocs_ ready!
> Name	Link
> 🔨 Latest commit	[936296e](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/commit/936296ea2d7022f5362e8d84b4ac734fb2b52733)
> 🔍 Latest deploy log	https://app.netlify.com/sites/oscsa-moocs/deploys/637393d999e9f70009d5962c
> 😎 Deploy Preview	https://deploy-preview-43--oscsa-moocs.netlify.app/
> 📱 Preview on mobile	
>  Toggle QR Code...
> _To edit notification comments on pull requests, go to your [Netlify site settings](https://app.netlify.com/sites/oscsa-moocs/settings/deploys#deploy-notifications)._

The netlify preview deploy link

**Pull request merged**
