### PR TITLE
[29/01/23] Project documentation - Setup/Introduction

### LINKED ISSUE #151: [05/01/2023] Project Documentation
#### Description

This is a sample outline for the MOOC's project documentation

**Introduction**
**Changelog (short preview of the milestones achieved in the project)**
**Design and architecture**
**Getting started**
   * Prerequisites
   * Installation Guide
   * Usage
   
**Project Folder structure**   
   * Directory structure
   * Folder functions
   * File naming conventions
   
**Local Environment setup**
**Contribution Guide/Workflow**
   * General Contrbution guides
          -   Raising issues
          -   Making changes
          -   Submittting Pull request
   * Frontend specific contribution guidelines
   * Backend specific contribution guidelines
   
**Code documentation**
   * Database model design
   * Function docs
   * API docs
 
**FAQs**

### PR DESCRIPTION
**Pull request by RealRichi3**
### Summary

Create technical documentation for project

Partially Fixes #151

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

### List of changes proposed in this PR (pull-request)
* *Create technical documentation for project*
* *Add necessary tutorial files*
* *Complete doc homepage*
* *Add contribution guides*
* *Add NEXT button feature*

### CODE REVIEW

**Comment by RealRichi3** [comment]
@sandygudie please how did you create the netlify preview for the blog site, i'd like something similar for the  code documentation

**Comment by RealRichi3** [comment]
I have completed the introduction, usage and getting started guide

**Comment by sandygudie** [comment]
Welldone Richie
You would have to open an account with Netlify to deploy projects there. 
I don’t mind doing it from my account if needed

Also you could try GitHub pages if the folder containing the work is in the root folder

Let me know which one suits you

**Comment by RealRichi3** [comment]
> Welldone Richie You would have to open an account with Netlify to deploy projects there. I don’t mind doing it from my account if needed
> 
> Also you could try GitHub pages if the folder containing the work is in the root folder
> 
> Let me know which one suits you

Thanks @sandygudie I'll open the netlify account

**Comment by BatoolMM** [comment]
Thank you, Sandy!

Yes, let us know if GH pages can be an easier option!

**Pull request merged**
