### PR TITLE
[02/01/2023] feat - Improved documentation for backend_API

### PR DESCRIPTION
**Pull request by RealRichi3**
### Summary
Improved code documentation for backend API using JSDoc node package

### List of changes proposed in this PR (pull-request)
* *Add detailed code documentation to controllers and major functions*
* *Controller documentation should include the controller required params, possible error cases and return values*
* *Add Gitbook integration*

### CODE REVIEW

**Comment by RealRichi3** [comment]
@BatoolMM i started improving on the documentation using JSDoc, please check it out the changes

**Comment by RealRichi3** [comment]
@BatoolMM, i tried the Gitbook integration, i successfully setup the folder structure and the required dependencies but when i try to run `npm run docs:prepare`. I keep getting this error
```bash
Installing GitBook 3.2.2
C:\Users\ADMIN\Desktop\Main\Repos\OSCSA\MOOCs\backend_API\node_modules\npm\node_modules\graceful-fs\polyfills.js:287
      if (cb) cb.apply(this, arguments)
                 ^

TypeError: cb.apply is not a function
    at C:\Users\ADMIN\Desktop\Main\Repos\OSCSA\MOOCs\backend_API\node_modules\npm\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqCallback.oncomplete (node:fs:207:5)
```

I tried looking for solutions online, i saw that it had something to do with old node versions, but my node version is v16.7.0

**Comment by BatoolMM** [comment]
Ahhh, can you open an issue on JSDocs repo? They might have other suggestions.

**Comment by RealRichi3** [comment]
Alright @BatoolMM, i just raised an issue in the JSDoc repo [here](https://github.com/jsdoc/jsdoc/issues/2031), hopefully i get suggestions

**Comment by RealRichi3** [comment]
@BatoolMM i thought maybe the error might be as a result of incompatible dependencies, so i tried it on gitpod, still same error 
```
added 21 packages, and audited 579 packages in 4s

52 vulnerabilities (2 low, 20 moderate, 18 high, 12 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```
I think some of the dependencies used by Gitbook have some vulnerabilities, dunno this might be the cause of the issue

**Pull request merged**
