### PR TITLE
add login-page , signup page , add routing and  improve file structure

### LINKED ISSUE #24: [14/10/2022]:   Create a Login Page and Sign Up Page (dev_team2 branch)
Corresponding PR at #31 
#### Description

Create a Login Page and Sign Up Page as illustrated in this [Design](https://www.figma.com/file/mkhBuJAS2arzy3wrbTZp2D/Simple-Landing-page-for-OSCSA%2C-with-Log-In-and-Sign-Up-Pages?node-id=1%3A2). This  issue was derived from #10  and is for dev_team2 branch

#### Which task are you working on?

- [ ]  Create a Login Page
- [ ]  Create a Sign Up Page

### What needs to be done?

✅ Use React to render the UI for the Login Page illustrated  [here](https://www.figma.com/file/mkhBuJAS2arzy3wrbTZp2D/Simple-Landing-page-for-OSCSA%2C-with-Log-In-and-Sign-Up-Pages?node-id=1%3A2).

✅ Use React to render the UI for the Forgot Passoword Page illustrated  [here](https://www.figma.com/file/mkhBuJAS2arzy3wrbTZp2D/Simple-Landing-page-for-OSCSA%2C-with-Log-In-and-Sign-Up-Pages?node-id=1%3A2).

### Who want to work on this issue?

@okerekechinweotito

### PR DESCRIPTION
**Pull request by okerekechinweotito**
### Summary

Fixes #24 

This PR is in sync with the latest frontend folder structure you just merged

I added a Login Page , Signup Page and enabled page routing. I improved folder structure by adding 'pages' and 'utils' folders for better efficient management of files. Pushed global styles to GlobalStyles.css

### List of changes proposed in this PR (pull-request)

* Added Login Page
* Added Signup Page
* Enabled routing with React-Router
* Added Pages and Utils folders
* Changed style structure so that Only Global styles should be linked to App.jsx and main.jsx

### What should a reviewer concentrate their feedback on?

- [ ] Inspect the Login and Sign Pages
- [ ] Test the page routing

Landing Page
Screenshot (38)

Login Page
Screenshot (39)

Sign up Page
Screenshot (40)

@BatoolMM

### CODE REVIEW

**Comment by okerekechinweotito** [comment]
@BatoolMM  This PR is ready to be merged to dev_team2 branch

**Comment by BatoolMM** [comment]
Thank you @okerekechinweotito, can also close the issue associated with PR?

**Comment by okerekechinweotito** [comment]
@BatoolMM I have closed the associated issue , thank you

**Comment by sandygudie** [comment]
@okerekechinweotito , your PR was not reviewed, 
You should not call for merging when it’s not reviewed. Please let’s follow the contribution guide.

@BatoolMM please I am reviewing frontend PRs for the `dev_team2. `I will call for merging when it’s reviewed and ready. Thank you

**Comment by okerekechinweotito** [comment]
@sandygudie 
I am following the contribution guide. Where did you inform us that you would be reviewing PRs for dev_team2 asides the one you did above. I was not aware.

Anyway, I will make sure my subsequent PRs are subjected to review by any of the team-members. Thank you

**Comment by BatoolMM** [comment]
@all-contributors please add @okerekechinweotito for test and infra

**Pull request merged**
