### PR TITLE
[1/2/2023] feat: Sphinx documentation for backend API

### PR DESCRIPTION
**Pull request by RealRichi3**
### Summary
Implemented sphinxjs code documentation for the backend API.

### List of changes proposed in this PR (pull-request)
* *Add required modules*
* *Add code documentation*
* *Attempted build with sphinx*

### What should a reviewer concentrate their feedback on?
- [ ] Everything looks ok?

I attempted build, it successfully created the HTML file, but I can't see any documentation there

image

### CODE REVIEW

**Comment by RealRichi3** [comment]
@BatoolMM i'm a bit confused, i only made like 5 commits in this PR but I think it has many other commits from previous changes, I think I made a mistake by not creating the `feat/sphinxjs` from the `backend_dev` branch, I'll raise another cleaner PR from a new branch

**Comment by BatoolMM** [comment]
No worries but make sure you reference this PR in the new one.

**Comment by RealRichi3** [comment]
alright

**Comment by RealRichi3** [comment]
@BatoolMM i think i know where the issue is from,
There's a new branch `backend_dev`
we had `dev_team2` before, I created two sub branches from it to form `dev_backend` and `dev_frontend` 
Only the `dev_team2` and its sub branches have all our previous commit history.

But the new `backend_dev` branch was created from the `main` branch, and the `main` branch doesn't have our changes from the contribution phase, it think that's why this PR has so many new changes

**Comment by RealRichi3** [comment]
@BatoolMM what do you think

**Comment by RealRichi3** [comment]
Should i make the big merge to add all the backend code to the `backend_dev` or should I just pull the most recent changes from the `main` branch into the `backend_dev` then clean up the frontend code

**Comment by BatoolMM** [comment]
That makes sense, I added log file to the main, that’s why the new branches are created from the main but since everything is merged to the mail now. 

Feel free to close the new `backend_dev` and `frontend_dev` and create it again from the mail (which now includes all changes merged). We will ned to add all this info to the `contributing.md` later on

**Comment by RealRichi3** [comment]
@BatoolMM alright then

**Pull request closed without merging**
