### PR TITLE
[02/01/2023] Isolate backend API src code

### PR DESCRIPTION
**Pull request by RealRichi3**
### Summary
Removed the frontend code and isolated only the backend code in `backend_dev` branch

### List of changes proposed in this PR (pull-request)
* *Removed frontend code from current branch*

### CODE REVIEW

**Comment by RealRichi3** [comment]
@BatoolMM, will you be handling reviewing the PR before merge, or can we continue to handle it?

**Review by BatoolMM — APPROVED** [review]

**Comment by BatoolMM** [comment]
Hi Richi, I am happy to merge this PR but the `backend_dev` branch will (in the future) have to be reabased with the main and include files from the front-end (at some point) as we link both front-end and backend together. Do you have in mind a different way or how do you envision this?

**Comment by RealRichi3** [comment]
ohh, i understand you now, i was thinking the frontend and backend code will remain in different branches forever
I'll revert the commit where I deleted the front end code then

**Comment by RealRichi3** [comment]
I think it's okay to merge now
@BatoolMM, what do you think

**Comment by BatoolMM** [comment]
Why is [CONTRIBUTING.md](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/148/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055) is removed?

**Comment by RealRichi3** [comment]
> Why is [CONTRIBUTING.md](https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/pull/148/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055) is removed?

I was of the mindset that the branch will strictly be for the backend API, and remember i already made a CONTRIBUTION guide for the backend API here #119

**Pull request closed without merging**
