### PR TITLE
28/11/2022 Added forgot password feature

### PR DESCRIPTION
**Pull request by sandygudie**
Fixes issues : https://github.com/Open-Science-Community-Saudi-Arabia/MOOCs/issues/126

Description
This PR includes
- Route set up and API for forgot password
-  forgot password UI page with authentication and validation
- Response and Error handling included

### CODE REVIEW

**Comment by RealRichi3** [comment]
I'll make some changes to the API, i think the user should manually enter a password reset code in a new page, together with the new password.

**Comment by sandygudie** [comment]
> I'll make some changes to the API, i think the user should manually enter a password reset code in a new page, together with the new password.

No, it should not be like that, the reset code /token received in the email will be send with the new password for the reset password endpoints.

**Comment by RealRichi3** [comment]
@sandygudie Here's what i had in mind,
/Forgotpassword: Send password reset code to users email, send access token to front end
/Resetpassword: will require password reset code, and new password in request body. Then attach the auth token to request header

**Comment by sandygudie** [comment]
@RealRichi3 
See these resources
https://codevoweb.com/forgot-reset-password-in-reactjs-and-axios/

**Comment by sandygudie** [comment]
> ohh, you mean
> 
> * i should just add the password reset code to the mail,
> * URL link should have the reset JWT token as URL params,
> * You'll send back the reset code and new password
> 
> Is this what you mean?

Yes, you will validate if the reset code with the password is the same with what you sent

**Comment by RealRichi3** [comment]
Sure, i'll make the changes and push the updated code

**Comment by RealRichi3** [comment]
I think if i do it this way, by sending a reset link, i'll have to render the final reset page from the backend

**Comment by RealRichi3** [comment]
@sandygudie, how best do you think it should be implemented

**Comment by sandygudie** [comment]
> I think if i do it this way, by sending a reset link, i'll have to render the final reset page from the backend

Do you mean the successful reset page?

**Comment by RealRichi3** [comment]
@sandygudie I created an issue for the intended change #133, please check it out

**Pull request merged**
