### PR TITLE
fixed grammer & punctuation in CONTRIBUTING.md #64

### PR DESCRIPTION
**Pull request by AminMusah**
Summary
Fixes #<64>

Corrected Spelling and Grammatical errors on the MOOCs/CONTRIBUTING.md #64.*

At the top section of the contribution.md, there are a few grammatical errors and missing punctuations.

* Change from This --> We welcome all contributions to the Open Science Community in Saudi Arabia. The contribution can be a [issue report](https://github.com/Open-Science-Community-Saudi-Arabia/Open-Science-Community-in-Saudi/issues)  or a [pull request](https://github.com/Open-Science-Community-Saudi-Arabia/Open-Science-Community-in-Saudi/pulls).

* To --> We welcome all contributions to the Open Science Community in Saudi Arabia. The contribution can be an [issue report](https://github.com/Open-Science-Community-Saudi-Arabia/Open-Science-Community-in-Saudi/issues)  or a [pull request](https://github.com/Open-Science-Community-Saudi-Arabia/Open-Science-Community-in-Saudi/pulls).

* From --> If there isn't one already, please create one so that others know you're working on this

* To -->  If there isn't one already, please create one so that others know you're working on it.

* From --> Make the necessary changes / additions within your forked repository.

* To -->  Make the necessary changes and additions / subtractions within your forked repository.

What should a reviewer concentrate their feedback on?
 looking out for Spelling and punctuations.
* [x] sentence construction

### CODE REVIEW

**Comment by Meekunn** [comment]
@AminMusah, I believe you are trying to create a checked box. You can edit your PR and use `[x]`. Note that X is in lowercase and there is no space between the letter and the square brackets. 
Also, put it in as a bullet point.  Here is a sample `- [x] How to create a checked box.` 
 - [x] How to create a checked box.

**Comment by BatoolMM** [comment]
@all-contributors please add @AminMusah for bug

**Comment by BatoolMM** [comment]
@all-contributors please add @Meekunn for review

**Comment by BatoolMM** [comment]
Thank you both for this PR, let me know when it's ready to be merged!

**Comment by AminMusah** [comment]
> @Meekunn Thank you very much, that was really helpful.

**Comment by Meekunn** [comment]
@AminMusah, you are welcome. 😊

**Review by Meekunn — APPROVED** [review]

**Comment by BatoolMM** [comment]
Brilliant, thank you again @Meekunn, for the review and @AminMusah, for catching up the grammar and typo!

**Pull request merged**
