### PR TITLE
[18/10/2022]: Backend API [feat] - Social signin with Google 

### LINKED ISSUE #48: [18/10/2022]: Backend API [feat] - Social signin with Google
Sub issue for #5
 
#### Description
Social signin feature with google

#### Which task are you working on?
- [ ] *Add social signin feature with Google*

### PR DESCRIPTION
**Pull request by RealRichi3**
### Summary
Added social sign in feature with google to backend API

Fixes #48

### List of changes proposed in this PR (pull-request)
* *Add social signin with google*

### CODE REVIEW

**Comment by RealRichi3** [comment]
@BatoolMM please review and merge

**Comment by RealRichi3** [comment]
@BatoolMM please review and merge

**Comment by BatoolMM** [comment]
@all-contributors please add @RealRichi3 for Infrastructure and ideas

**Comment by BatoolMM** [comment]
@RealRichi3 please add @RealRichi3 for Project Management

**Review by JesperKawuma — COMMENTED** [review]
Woow!! @RealRichi3, this is real magic going on here. I literally know nothing when it comes to backend development, could you please direct me to any resource that can help, I also wish to be a magician like you.

**Comment by RealRichi3** [comment]
Thanks @JesperKawuma, you can check out MERN stack course by coding addict on YouTube

**Comment by JesperKawuma** [comment]
Thanks @RealRichi3,

**Pull request merged**
